### ISSUE TITLE
Ara_Broker_Reputations.lua:616: attempt to call method 'SetGradientAlpha' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [AraBroker/Ara_Broker_Reputations#1]
Running r56 and using with Bazooka. I'm getting the following error when I mouse over the LDB element on the Bazooka bar. Thanks.

8x ...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:616: attempt to call method 'SetGradientAlpha' (a nil value)
[string "@Interface/AddOns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:616: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:596>
[string "@Interface/AddOns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:644: in function `OnEnter'
[string "@Interface/AddOns/Bazooka/Bazooka.lua"]:1582: in function `showTip'
[string "@Interface/AddOns/Bazooka/Bazooka.lua"]:1387: in function <Interface/AddOns/Bazooka/Bazooka.lua:1378>

Locals:
cfg = <table> {
 if_iconSize = 113
 classification_rare = "%s|r (Rare) "
 classification_rareelite = "+%s|r (Rare) "
 classification_elite = "+%s "
 optionsBottom = 773.500000
 left = 1782.166748
 showGuildRank = true
 top = 138.666855
 optionsLeft = 784.666870
 targetYouText = "<<YOU>>"
 classification_trivial = "~%s "
 classification_minus = "-%s "
 classification_worldboss = "%s|r (Boss) "
 showPlayerGender = true
 classification_normal = "%s "
}
(*temporary) = nil
(*temporary) = Texture {
 0 = <userdata>
}
(*temporary) = "VERTICAL"
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0.800000
(*temporary) = 0.800000
(*temporary) = 0.800000
(*temporary) = 0.200000
(*temporary) = "attempt to call method 'SetGradientAlpha' (a nil value)"
config = <table> {
 blizzColorsDefault = false
 Argent Dawn - Alteryx = <table> {
 }
 Cenarius - Nimriel = <table> {
 }
 textValues = false
 Cenarius - Lysra = <table> {
 }
 Cenarius - Illyriana = <table> {
 }
 textPerc = true
 Cenarius - Cryska = <table> {
 }
 barTexture = "TargetingFrame\UI-StatusBar"
 textStanding = false
 Wyrmrest Accord - Crythe = <table> {
 }
 asciiBar = "dualColors"
 Cenarius - Illinari = <table> {
 }
 Argent Dawn - Luciferhawk = <table> {
 }
 textBlock = "factionNameColor"
 scale = 1
 blizzColorsInsteadBroker = false
 Cenarius - Hoshino = <table> {
 }
 blizzardColors = <table> {
 }
 showRepToGo = true
 textFactionColor = true
 Cenarius - Neirenn = <table> {
 }
 autoSwitch = true
 Argent Dawn - Kythaela = <table> {
 }
 showParagonCount = true
 useTipTacSkin = true
 Cenarius - Darcsen = <table> {
 }
 blockDisplay = "text"
 Argent Dawn - Aurelia = <table> {
 }
 asciiColors = <table> {
 }
 textSession = false
 textFaction = true
 blizzColorsInstead = false
 showSessionGain = true
 textParagon = false
 Cenarius - Ravenwood = <table> {
 }
 showRawInstead = true
 textToGo = false
 showSeparateValues = true
 Argent Dawn - Neisa = <table> {
 }
 Wyrmrest Accord - Alteryx = <table> {
 }
 Cenarius - Celandine = <table> {
 }
}
tiptacBG = <table> {
 bgFile = "Buttons\WHITE8X8"
 tile = false
 edgeSize = 14
 edgeFile = "Tooltips\UI-Tooltip-Border"
 insets = <table> {
 }
}
f = AraReputation {
 0 = <userdata>
 Center = Texture {
 }
 TopLeftCorner = Texture {
 }
 onBlock = true
 PLAYER_ENTERING_WORLD = <function> defined @Interface/AddOns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:1071
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 AddModule = <function> defined @Interface/AddOns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:107
 BottomEdge = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
 SetupConfigMenu = <function> defined @Interface/AddOns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:871
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 backdropInfo = <table> {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 CHAT_MSG_COMBAT_FACTION_CHANGE = <function> defined @Interface/AddOns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:840
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBorderB

**Comment by frozn** [comment]
Inspiration for fix see here: https://github.com/frozn/TipTac/issues/121#issuecomment-1301727246

**Comment by bubfeeld** [comment]
Hey I am the guy from the tiptac thread, with Frozn's tips , I did the following =
In Ara_Broker_Reputation.lua  on line 608::
Replace 
tiptacGradient:SetTexture(1,1,1,1)
with
tiptacGradient:SetTexture([[Interface\AddOns\TipTac\media\gradient]])

then on line 610::

tiptacGradient:SetGradientAlpha("VERTICAL",0,0,0,0,unpack(cfg.gradientColor))
with
tiptacGradient:SetVertexColor(unpack(cfg.gradientColor))


It may help, I am not getting the error i listed in that thread, and my reps display upon mouseover.

I use ChocolateBar for reference too.

**Comment by mightykong** [comment]
I'm digging into this now, I'll post a fix once I have it sorted

**Comment by mightykong** [comment]
Fixed with r57 version
