### ISSUE TITLE
Values displayed on LDB button are not updating

### ISSUE THREAD

**Issue by tflo** [AraBroker/Ara_Broker_Reputations#10]
It seems the the values (here: percentage) displayed on the LDB button are not updating:

<img width="792" alt="WoWScrnShot_011323_000718" src="https://user-images.githubusercontent.com/1410282/212201659-a2f5f158-2a7c-450c-a594-58037e16548f.png">

It shows 3%, but in reality I was at ~25% (see tooltip). Via settings, I disabled and re-enabled the percentage display on the button, _and then_ it did update to 25%.

– Tom

**Comment by tflo** [comment]
PS: If your intention is to save some CPU cycles, this is OK for me. But then it should update when I call the tooltip. (Not only when I change the settings.)

**Comment by mightykong** [comment]
Are you leaving the header it's in collapsed, and then expanding when you want to look at the full rep?

**Comment by mightykong** [comment]
I'm really trying to replicate how you got these out of sync.  I can't seem to do it.  It's in that category of "I'm not complaining but that's amazing" things.

I'll play around with it and see if it's something I can find.  

In the meantime, please let me know if you're doing things like collapsing headers on factions that you're gaining rep on, making factions inactive, then reactivating them, etc.

**Comment by tflo** [comment]
> let me know if you're doing things like collapsing headers on factions that you're gaining rep on

As far as I remember, I have never collapsed the DF header on the toons that are actually in DF (like the one where it happened).

It is possible that inbetween I got a few rep points on a collapsed header faction (but not DF), e.g. one of the Shadowlands factions when back at the mission table in Shadowlands. But I guess that's not what you mean.

> making factions inactive, then reactivating them

Never made any faction inactive. (Had to enable the tips to see how I can do that.)

> , etc.

Well, that's a difficult question …

---

Just checked my DF factions now, and everything seems in sync with the button text. Maybe it was a unique thing that happens only on a single day of the year, but only if it's raining and full moon ;)

**Comment by mightykong** [comment]
Please review to see if this issue persists in r64 which will be posted later today.  If we can find a way to reliably replicate this, please let me know and reopen. I'm going to close this issue for now.
