### ISSUE TITLE
TWW pre patch

### ISSUE THREAD

**Issue by bubfeeld** [AraBroker/Ara_Broker_Reputations#14]
It gives errors on mouseover and wont display anything, sucks after all the work we did a couple of months ago,lol

These are the copy pasted errors another user posted on the addon page, but i get similiar errors as well.

Got some errors on retail after the WW Prepatch:

 

First one:

 

3x ...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:1190: attempt to call global 'GetWatchedFactionInfo' (a nil value)

[string "@Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:1190: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:1187>

 

Locals:

(*temporary) = nil

(*temporary) = "attempt to call global 'GetWatchedFactionInfo' (a nil value)"

f = AraReputation {

}

watchedFaction = nil

**Comment by bubfeeld** [comment]
1x ...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:459: attempt to call global 'GetNumFactions' (a nil value)

[string "@Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:459: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:442>

[string "@Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:742: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:734>

[string "@Titan/TitanLDB.lua"]:356: in function <Titan/TitanLDB.lua:315>

 

Locals:

self = nil

menuFactionWidth = 0

menuValuesWidth = 0

menuToGoWidth = 0

menuSessionWidth = 0

itemFactionWidth = nil

itemValuesWidth = nil

itemToGoWidth = nil

itemSessionWidth = nil

button = nil

inactive = nil

standingText = ""

inactive = nil

skip = nil

skipChild = nil

(*temporary) = 1

(*temporary) = nil

(*temporary) = "attempt to call global 'GetNumFactions' (a nil value)"

f = AraReputation {

 BottomLeftCorner = Texture {

 }

 RightEdge = Texture {

 }

 onBlock = true

 Center = Texture {

 }

 TopEdge = Texture {

 }

 backdropInfo = <table> {

 }

 PixelSnapDisabled = true

 BottomEdge = Texture {

 }

 TopRightCorner = Texture {

 }

 TopLeftCorner = Texture {

 }

 LeftEdge = Texture {

 }

 BottomRightCorner = Texture {

 }

}

config = <table> {

 

**** all characters known by the addon  ***

}

MAX_ENTRIES = 72

GAP = 10

BUTTON_HEIGHT = 14

factions = <table> {

}

tables = <table> {

}

nbEntries = 0

GetFactionInfo = nil

char = <table> {

 collapsedHeaders = <table> {

 }

}

FACTION_INACTIVE = "Inactive"

buttons = <table> {

}

watchedFaction = nil

focusedButton = nil

SIMPLE_BAR_WIDTH = 110

ICON_SIZE = 13

TEXT_OFFSET =

**Comment by mightykong** [comment]
I'll take a look, but this isn't going to be a quick fix.  Looks like they changed a bunch of the reputation function names.  Shocker, they just can't leave well enough alone.  I'm also pretty busy, probably won't see an update for a few days as I'm mostly playing SoD.  I'll get there, but it's not going to be today.

**Comment by mightykong** [comment]
Try this file as a temp fix for now:  https://github.com/AraBroker/Ara_Broker_Reputations/blob/master/Ara_Broker_Reputations.lua

This is at least allowing it to load for me.  However, I have not played and gained rep, so not sure if it's working properly still

Also, the Renowns aren't showing anymore in the rep pane.  I've checked other Rep addons and it's doing the same there.  This will take some investigations to fix.  It could be a bug by Blizzard, or they changed the way to retrieve them.

**Comment by mightykong** [comment]
You can try downloading the file again: https://github.com/AraBroker/Ara_Broker_Reputations/blob/master/Ara_Broker_Reputations.lua
 
The Renowns are now tracking, but you have to gain rep for them to show (Blizzard issue apparently).  Gains should be working now too.  Let me know if you hit anything else.  I need to test this and back port this to classic to make sure nothing has been broken there too

**Comment by viralanomaly** [comment]
I'll give it a test for you, too, since I've been doing a bunch of older quests that are giving me rep.

**Comment by mightykong** [comment]
r81 should fix TWW initial issues.  Still not sure how I may want to handle a differentiation between Account Wide and Personal Rep (like being able to filter on that).  But this should fix all autoswitching issues and bar issues as well.
