### ISSUE TITLE
New Error in latest version R81

### ISSUE THREAD

**Issue by ala75** [AraBroker/Ara_Broker_Reputations#15]
2x ...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:986: bad argument #1 to 'match' (string expected, got nil)
[string "=[C]"]: in function `match'
[string "@Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:986: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:977>
[string "=(tail call)"]: ?

Locals:
(*temporary) = "Your Warband's reputation with Valdrakken Accord increased by 75."
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by mightykong** [comment]
Fixed with r82
