### ISSUE TITLE
Ara Broker rep

### ISSUE THREAD

**Issue by Oldfartwarc** [AraBroker/Ara_Broker_Reputations#16]
It wuld be useful if on your speil on Curse if you included some basic command lines for suers
eg
/config
/help
/show
etc

As it is I'm told that your mod is runnign but  can't see or utilise it.

Thanks
Mike (or maybe I'm just think!)

**Comment by Oldfartwarc** [comment]
thick even

**Comment by mightykong** [comment]
I can look into that, but I am not the original author of the mod and that wasn't in the original design.  The mod REQUIRES a broker display. Titan Panel, Chocolate, etc.  It won't display anywhere unless one is installed.

If you have a broker display installed, then make sure that the config of the Broker Display had Ara Reputations enabled.  I know Titan Panel requires this.

**Comment by mightykong** [comment]
Added usage information on the project description for now

**Comment by Oldfartwarc** [comment]
Cheers , I've used Titan in the past, so may reinstall, though I use Elvui  pretty much across the board these days to avoid conflicts. Thanks for being so prompt, I'll see how it goes. Probably wait for the new expansion  to bed in before I do too much.

Cheers
Mike 🙂

________________________________

**Comment by mightykong** [comment]
I have no information on making it work with Elvui, as I've not ever used it.  However, if it contains a broker display, make sure Ara Reputations is enabled in it.
