### ISSUE TITLE
New Error in R82

### ISSUE THREAD

**Issue by ala75** [AraBroker/Ara_Broker_Reputations#17]
Did a flyby in Darkshore Warfront and after killing a rare a new error popped up:

2x ...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:1036: attempt to call field 'SetWatchedFaction' (a nil value)
[string "@Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:1036: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:969>
[string "=(tail call)"]: ?

Locals:
self = AraReputation {
}
msg = "Reputation with Council of Exarchs increased by 500."
faction = "Council of Exarchs"
value = 500
neg = nil
updated = nil
switch = true
scannedFactions = true
(*temporary) = nil
(*temporary) = 1731
(*temporary) = "attempt to call field 'SetWatchedFaction' (a nil value)"
fsInc = "Reputation with (.*) increased by ([0-9]+)."
fsInc2 = "Reputation with (.*) increased by ([0-9]+)."
fsInc3 = "Reputation with (.*) increased."
fsDec = "Reputation with (.*) decreased by ([0-9]+)."
config = <table> {

**** all characters *** 

 {
 }
 blizzColorsInstead = false
}
GUILD = "Guild"
barFactionHidden = true
modules = <table> {
}
factionIdtable = <table> {
 Gilneas = 1134
 Stormwind = 72
 Steamwheedle Cartel = 169
 Classic = 1118
 Ratchet = 470
 Ironforge = 47
 Alliance Vanguard = 1037
 Wrath of the Lich King = 1097
 Emperor Shaohao = 1492
 Dreamweavers = 1883
 Mists of Pandaria = 1245
 The Wyrmrest Accord = 1091
 Alliance = 469
 Tushui Pandaren = 1353
 Wildhammer Clan = 1174
 Exodar = 930
 Keepers of Time = 989
 The Burning Crusade = 980
 Chromie = 2135
 The Scale of the Sands = 990
 Council

**Comment by mightykong** [comment]
Is your Council of Exarchs reputation set as Inactive?

**Comment by mightykong** [comment]
If not set as Inactive, is it under a collapsed header?

**Comment by mightykong** [comment]
Please replace line 1036 from this:

C_Reputation.SetWatchedFaction(factionIdtable[faction])

to this

C_Reputation.SetWatchedFactionByID(factionIdtable[faction])

and report back when you can

**Comment by ala75** [comment]
TBh this feels very Blizzard buggy. I just checked the 3 chars i have been in Darkshore with (only one got that error). On none of them i can see this faction. I also dont understand this happends in Darkshore (BFA Warfront) and the error mentions a Warlord of Draenor faction.

q: Is your Council of Exarchs reputation set as Inactive?
a: No, that faction i cant even see in the Blizzard reputation menu

q: If not set as Inactive, is it under a collapsed header?
a: just triple checked those 3 characters, all uncollepsed, no Council of Exarchs there

ill adjust line 1036 like you suggested. ill test again after reset since the stuff i do in the warfront are weekly locked :S

**Comment by ala75** [comment]
Mmm. Just thinking. Those chars had nothing watched while i logged in (auto switch reputation gain is enabled across all chars). Could it be that i got that rep from killing a mob that gives that specific rep, but the reputation/faction isnt unlocked for that chars. Meaning the addon sees rep, trying to switch, but the faction isnt ulocked so it cant switch because its unavaileble?

While testing abit i found another error by justy clicking reputations in the broker menu. ill post that new issue

**Comment by mightykong** [comment]
I found the issue, it has to do with hidden/inactive/collaped reps.  Fix coming with r83

**Comment by ala75** [comment]
your the best, sorry for posting so many things i stumble in to :(f

**Comment by mightykong** [comment]
Fixed in r83
