### ISSUE TITLE
Another error popped in R82

### ISSUE THREAD

**Issue by ala75** [AraBroker/Ara_Broker_Reputations#18]
Just clicking a few factions in the broker menu while i was testing your suggestion for the other error that popped.  This error pops:

2x ...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:950: attempt to index local 'color' (a nil value)
[string "@Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:950: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:815>
[string "@Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:188: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:183>
[string "@Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:209: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:191>

Locals:
info = <table> {
 standingId = ""
 barValue = 9000
 name = "The Honorbound"
 bottomValue = 5
 topValue = 3000
 factionId = 3825
}
repColors = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 paragon = <table> {
 }
 renown = <table> {
 }
}
value = 8995
max = 2995
color = nil
standingText = ""
hasRewardPending = nil
balance = 0
texture = nil
perc = 300
isCapped = false
level = ""
c1 = nil
c2 = nil
icon = "Interface\Icons\ability_warrior_warcry"
asciiColor = "|cffffff00"
(*temporary) = <table> {
 1 = "|cffffff00|r"
 2 = "300%|r"
}
(*temporary) = 1
(*temporary) = "|cff%.2x%.2x%.2x%s|r"
(*temporary) = 300
(*temporary) = "300%|r"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'color' (a nil value)"
firstCall = false
factionIdtable = <table> {
 Frostwolf Orcs = 1445
 Cenarion Expedition = 942
 The Kalu'ak = 1073
 Horde Forces = 892
 Ratchet = 470
 Talanji's Expedition = 2156
 Zandalari Empire = 2103
 The Ashen Verdict = 1156
 Silvermoon City = 911
 Orgrimmar = 76
 Undercity = 68
 Frostwolf Clan = 729
 The Burning Crusade = 980
 Arakkoa Outcasts = 1515
 Kirin Tor = 1090
 Valarjar = 1948
 Horde = 67
 Battle for Azeroth = 2104
 The Taunka = 1064
 Champions of Azeroth = 2164
 Huojin Pandaren = 1352
 Gadgetzan = 369
 Everlook = 577
 Booty Bay = 21
 The Honorbound = 2157
 Steamwheedle Cartel = 169
 Wrath of the Lich King = 1097
 The Wyrmrest Accord = 1091
 Thunder Bluff = 81
 The Hand of Vengeance = 1067
 Darkspear Trolls = 530
 Bilgewater Cartel = 1133
 Keepers of Time = 989
 Tortollan Seekers = 2163
 Argent Crusade = 1106
 Classic = 1118
 The Sunreavers = 1124
 Dreamweavers = 1883
 Mists of Pandaria = 1245
 Legion = 1834
 Warsong Offensive = 1085
 Shado-Pan = 1270
 The Wardens = 1894
 Horde Expedition = 1052
 Forest Hozen = 1228
 Warlords of Draenor = 1444
}
sessionStartMajorFaction = <table> {
}
sessionStart = <table> {
 1073 = 11220
 1270 = 5
 1085 = 11010
 76 = 14635
 1156 = 4394
 1097 = 0
 911 = 9599
 980 = 0
 1444 = 0
 1133 = 14187
 1515 = 1500
 1834 = 0
 1090 = 4017
 2156 = 0
 2164 = 2000
 1228 = 5100
 1106 = 195
 1118 = 0
 21 = 750
 2157 = 3825
 1445 = 5160
 67 = 14161
 1894 = 600
 68 = 39120
 1091 = 4173
 2103 = 20000
 530 = 8999
 1052 = 10627
 1245 = 0
 3825 = 9000
 1064 = 10308
 2104 = 0
 729 = 0
 369 = 750
 989 = 10
 577 = 750
 169 = 750
 470 = 750
 892 = 0
 1352 = 8999
 81 = 8999
 1883 = 9770
 942 = 4230
 1948 = 750
 1067 = 5313
 1124 = 5320
 2163 = 2760
}
lastReps = <table> {
 1073 = 11220
 1270 = 5
 1085 = 11010
 76 = 14635
 1156 = 4394
 1097 = 0
 911 = 9599
 980 = 0
 1444 = 0
 1133 = 14187
 1515 = 1500
 1834 = 0
 1090 = 4017
 2156 = 0
 2164 = 2000
 1228 = 5100
 1106 = 195
 1118 = 0
 21 = 750
 2157 = 3825
 1445 = 5160
 67 = 14161
 1894 = 600
 68 = 39120
 1091 = 4173
 2103 = 20000
 530 = 8999
 1052 = 10627
 1245 = 0
 1064 = 10308
 2104 = 0
 729 = 0
 369 = 750
 989 = 10
 577 = 750
 169 = 750
 470 = 750
 892 = 0
 1352 = 8999
 81 = 8999
 1883 = 9770
 942 = 4230
 1948 = 750
 1067 = 5313
 1124 = 5320
 2163 = 2760
}
watchedFaction = nil
watchedIndex = 0
updateBeforeBlizzard = false
barFaction = nil
barFactionHidden = nil
config = <table> {
 
 *** chars ***
 }
 blo

**Comment by mightykong** [comment]
Fixed in r83
