### ISSUE TITLE
Ara_Broker_Reputations.lua:1059: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [AraBroker/Ara_Broker_Reputations#19]
While questing I received the following error when I talked to an NPC to turn in a quest. Thanks.

1x ...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:1059: attempt to index field '?' (a nil value)
[string "@Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:1059: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:1056>
[string "=(tail call)"]: ?

Locals:
self = AraReputation {
}
factionId = 2590
newRenownLevel = 1
oldRenownLevel = 0
data = <table> {
 unlockDescription = "Complete the quest Impossible Odds in Dornogal in Isle of Dorn"
 renownReputationEarned = 0
 bountySetID = 120
 renownLevel = 1
 isUnlocked = false
 factionID = 2590
 expansionID = 10
 celebrationSoundKit = 213204
 name = "Council of Dornogal"
 renownFanfareSoundKitID = 213208
 uiPriority = 14
 textureKit = "storm"
 renownLevelThreshold = 2500
}
(*temporary) = nil
(*temporary) = <table> {
 start = 0
 max = 2500
}
(*temporary) = 2500
(*temporary) = "attempt to index field '?' (a nil value)"
sessionStartMajorFaction = <table> {
 2574 = <table> {
 }
 2507 = <table> {
 }
 2564 = <table> {
 }
 2510 = <table> {
 }
 2503 = <table> {
 }
 2511 = <table> {
 }
}

**Comment by Yanngo** [comment]
In file Ara_Broker_Reputations.lua replace in line 1069
GetAddOnMetadata
with
C_AddOns.GetAddOnMetadata

**Comment by mightykong** [comment]
Sorry for delay, I've actually been taking a bit of a sabbatical from WoW of late and enjoying other pursuits away from a computer. I'll take a look at this in the next day or so.

**Comment by mightykong** [comment]
Still researching this one, haven't been able to reproduce so far.

**Comment by Ookami313** [comment]
It seems to only happen when I first talked to a quest giver of a new faction I haven't started to earn renown for yet. I've only seen it a couple of times and the last one was the day before yesterday when I started working on the Hallowfall zone and faction.

**Comment by mightykong** [comment]
Ok, I've just started playing as I've been doing other things. I'll keep an eye out for it. I've made a lot of fixes already so I may have already fixed it as a byproduct in r85. But I'll keep watching for it.

**Comment by Ookami313** [comment]
I just received the following error after obtaining rep with new factions. I killed a rare, got the reputation from it and the error popped.

![image](https://github.com/user-attachments/assets/89ff33dd-f88d-48ef-a861-a6c7ddef3b18)

1x ...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:1082: attempt to index field '?' (a nil value)
[string "@Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:1082: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:1079>
[string "=(tail call)"]: ?

Locals:
self = AraReputation {
}
factionId = 2600
newRenownLevel = 1
oldRenownLevel = 0
data = <table> {
 unlockDescription = "Complete the quest The Tangled Web in The Weaver's Lair in Azj-Kahet"
 renownReputationEarned = 0
 bountySetID = 120
 renownLevel = 1
 isUnlocked = false
 factionID = 2600
 expansionID = 10
 celebrationSoundKit = 213204
 name = "The Severed Threads"
 renownFanfareSoundKitID = 213208
 uiPriority = 11
 textureKit = "web"
 renownLevelThreshold = 2500
}
(*temporary) = nil
(*temporary) = <table> {
 start = 0
 max = 2500
}
(*temporary) = 2500
(*temporary) = "attempt to index field '?' (a nil value)"
sessionStartMajorFaction = <table> {
 2574 = <table> {
 }
 2507 = <table> {
 }
 2590 = <table> {
 }
 2570 = <table> {
 }
 2503 = <table> {
 }
 2511 = <table> {
 }
 2594 = <table> {
 }
 2510 = <table> {
 }
 2564 = <table> {
 }
}

**Comment by mightykong** [comment]
Is this with r85 that I just released?

**Comment by Ookami313** [comment]
Yes. Currently running r85.

**Comment by mightykong** [comment]
Ok, I'm looking through the code, just need to be able to test it once I find a fix.

**Comment by mightykong** [comment]
Fixed in r86
