### ISSUE TITLE
reputationInfo error

### ISSUE THREAD

**Issue by Trajin** [AraBroker/Ara_Broker_Reputations#2]
86x Usage: local reputationInfo = C_GossipInfo.GetFriendshipReputation(friendshipFactionID)
[string "=[C]"]: in function `GetFriendshipReputation'
[string "@Interface/AddOns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:669: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:650>
[string "@Interface/AddOns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:1058: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:1054>

Locals:
(*temporary) = "Usage: local reputationInfo = C_GossipInfo.GetFriendshipReputation(friendshipFactionID)"

I was looking at the LUA file and saw your notes on this and the reasoning for why it's happening.

**Comment by mightykong** [comment]
What version are you using?  The latest?  
Is this the whole error?

**Comment by mightykong** [comment]
Trying to gather more information to troubleshoot

**Comment by mightykong** [comment]
Closing this issue, as it appears user was running version prior to r56 and had problems with Inactive factions
