### ISSUE TITLE
error popping when rightclicking for config

### ISSUE THREAD

**Issue by ala75** [AraBroker/Ara_Broker_Reputations#20]
got this error popping when rightclicking on the broker the config options. I don;t know if its titan or ara_broker: (

1x ...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:1069: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:1069: in function `SetupConfigMenu'
[string "@Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:729: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:724>
[string "@Titan/TitanLDB.lua"]:303: in function <Titan/TitanLDB.lua:301>

Locals:
self = AraReputation {
 BottomLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 onBlock = true
 Center = Texture {
 }
 TopEdge = Texture {
 }
 backdropInfo = <table> {
 }
 PixelSnapDisabled = true
 BottomEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 LeftEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
}
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = "Ara Reputations %s"
(*temporary) = nil
(*temporary) = "Ara_Broker_Reputations"
(*temporary) = "Version"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"
configMenu = AraReputationConfigMenu {
 displayMode = "MENU"
}
options = nil
addonName = "Ara_Broker_Reputations"
wowtextversion = "Retail"
textures = nil
defaultTexture = "Interface\TargetingFrame\UI-StatusBar"
info = <table> {
}
config = <table> {

 *** all characters ***
 }
 blizzColorsInstead = false
}
SetOption = nil
levels =

**Comment by mightykong** [comment]
Sorry for delay, I've actually been taking a bit of a sabbatical from WoW of late and enjoying other pursuits away from a computer. I'll get this pushed into the code in the next day or so.

**Comment by mightykong** [comment]
Fixed in r85
