### ISSUE TITLE
Weird interference with PitBull via AceConfig

### ISSUE THREAD

**Issue by tflo** [AraBroker/Ara_Broker_Reputations#5]
When Ara is loaded, I'm unable to get into the config of PitBull4 (config frame opens, but nothing is drawn after the first two drop-down menus). This is definitely an interference between Ara and PitBull, no other addons needed to reproduce.

No idea what is going on here. Maybe some leaked variable? Seeing this with r60alpha, and also with the current r60beta. 

This error gets logged:

```text
1x ...nfig-3.0/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua:221: Method renown doesn't exist in handler for type order
[string "=[C]"]: ?
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:221: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:164>
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:336: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:310>
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1006: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1002>
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1025: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1002>
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1059: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1036>
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1726: in function `FeedGroup'
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1919: in function `Open'
[string "@PitBull4/Options/Options.lua"]:60: in function <PitBull4/Options/Options.lua:59>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@FrameXML/ChatFrame.lua"]:5224: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4888: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4924: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>
[string "=[C]"]: ?

Locals:
(*temporary) = "Method renown doesn't exist in handler for type order"

```

– Tom

**Comment by mightykong** [comment]
Is this Pitbull Unit Frames?  Any other modules for Pitbull you're running?

**Comment by tflo** [comment]
Yep, [this](https://www.curseforge.com/wow/addons/pitbull-unit-frames-4-0) one. No other modules, not even the PitBull4_DogTagTexts module, which comes with the standard download.

As said, it occurs with PitBull4 and Ara as the only 2 loaded addons. (And no, with PitBull alone the error does not occur ;)
Can't you reproduce it on your install? My client is 10.0.2(47213), PitBull is 4.2.26, Ara is r60-beta.

**Comment by mightykong** [comment]
What broker display are you using?  Haven't tried to reproduce it, probably won't be able to look at it for a day or so.

**Comment by tflo** [comment]
I'm using Bazooka. But this shouldn't play a role, since the error occurs also without any other addons (also without any Broker display), directly when opening the PitBull config with `/pb4`.

To exclude any library issues, I just renamed my normal AddOns folder and logged in with a fresh AddOns folder _only containing Ara and PitBull:_

![WoWScrnShot_010223_005322-pty-fs8](https://user-images.githubusercontent.com/1410282/210187845-8cda34ab-21c1-4d39-96c7-612fa9575dea.png)

But the error still occurs.

The error log is now:

```text
Message: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:221: Method renown doesn't exist in handler for type order
Time: Mon Jan  2 00:55:30 2023
Count: 3
Stack: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:221: Method renown doesn't exist in handler for type order
[string "=[C]"]: ?
[string "@Interface/AddOns/PitBull4/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:221: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:164>
[string "@Interface/AddOns/PitBull4/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:336: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:310>
[string "@Interface/AddOns/PitBull4/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1006: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1002>
[string "@Interface/AddOns/PitBull4/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1025: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1002>
[string "@Interface/AddOns/PitBull4/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1059: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1036>
[string "@Interface/AddOns/PitBull4/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1726: in function `FeedGroup'
[string "@Interface/AddOns/PitBull4/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1919: in function `Open'
[string "@Interface/AddOns/PitBull4/Options/Options.lua"]:60: in function <Interface/AddOns/PitBull4/Options/Options.lua:59>
[string "=(tail call)"]: ?
[string "@Interface/FrameXML/ChatFrame.lua"]:5224: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4888: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4924: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals: (*temporary) = "Method renown doesn't exist in handler for type order"
```

You'll notice that the game is now using `AceConfig-3.0` from PitBull's Libs folder (instead of `AceConfig-3.0-3`  from BagSync's Libs). But this doesn't seem to be of any importance.

**Comment by tflo** [comment]
To illustrate the effect of the error:

This is the regular PB4 config frame:

![WoWScrnShot_010223_010719-pty-pty-fs8](https://user-images.githubusercontent.com/1410282/210188149-c58549f7-bfac-4337-b355-e5ff79339af4.png)

And this with Ara loaded:

![WoWScrnShot_010223_010746-pty-pty-fs8](https://user-images.githubusercontent.com/1410282/210188156-01c24f03-b034-4c5f-8c2f-09e5c88139c0.png)

The error gets thrown when this frame opens.

**Comment by mightykong** [comment]
Download the beta2 version of the lua here:  https://github.com/AraBroker/Ara_Broker_Reputations/blob/master/Ara_Broker_Reputations.lua

It's fixed it in my setup, but I haven't tested it much because I don't use PitBull.  Let me know if it fixes it for you.

**Comment by tflo** [comment]
Haven't tested it much either, but PB4 config opens normally now. So, I would say it's fixed ;)

What was it then?

**Comment by mightykong** [comment]
Ara makes some entries into the color palette.  This was done with numerical elements (an array), but the new code for the latest update switched that to text elements (hash table).  Apparently, it's not a variable collision problem, as much as PitBull doesn't seem to like that.  No other Addon seems to have complained, but I reverted it back to numbers and that seems to have helped.

**Comment by tflo** [comment]
> No other Addon seems to have complained

Yes, I was wondering if PitBull might not have been the only addon affected. It was coincidence that I opened the configuration of PitBull the same day I first installed Ara (I don't open it often), and I have 67 other instances of _AceConfigDialog-3.0.lua_ in my active AddOns folder, of which I've opened maybe 5 since then...
