### ISSUE TITLE
LUA error having hit renown 30 with Tuskarr

### ISSUE THREAD

**Issue by Epidemedabear** [AraBroker/Ara_Broker_Reputations#8]
I just hit renown 30, max renown for them, and now I get the following error whenever I mouseover the broker display

`7x ...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:400: attempt to call global 'MajorFactionMaxLevel' (a nil value)
[string "@Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:400: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:396>
[string "@Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:837: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:754>
[string "@Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:947: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:944>
[string "=(tail call)"]: ?

Locals:
factionId = 2511
standingId = 5
(*temporary) = 30
(*temporary) = nil
(*temporary) = 2511
(*temporary) = "attempt to call global 'MajorFactionMaxLevel' (a nil value)"
IsMajorFaction = <function> defined =[C]:-1
HasMaximumRenown = <function> defined =[C]:-1
GetCurrentRenownLevel = <function> defined =[C]:-1
GetFriendshipReputation = <function> defined @Ara_Broker_Reputations/Ara_Broker_Reputations.lua:266
`

For reference the default reputation tab shows that paragon rep requirement increases from 2500 to 7500

![image](https://user-images.githubusercontent.com/60220665/211807169-ce9645c4-b518-4bf1-917d-4ebdc8d2ae4d.png)

**Comment by mightykong** [comment]
I pushed a commit to address, but I have no way of testing it.  I haven't reached max yet.  

Can you download: https://github.com/AraBroker/Ara_Broker_Reputations/blob/master/Ara_Broker_Reputations.lua and replace the file in the addons folder and see if that corrects?

**Comment by Epidemedabear** [comment]
Im no longer getting any errors, which is good :)
Its not tracking paragon rep with the Tuskarr though, its showing me as at renown 30, not telling me that Im currently 2065/7500 through the paragon level.
In addition if I have Tuskarr as my tracked rep any rep with other factions doesn't cause the tracker to auto switch to the new faction. Testing with any of the other non capped factions tracked it does auto switch when gaining rep with another faction unless I gain Tuskarr rep.

**Comment by mightykong** [comment]
Yeah, that's probably going to take some additional work to make right.  At least now it's not popping errors.  

Part of this is not knowing how they were going to manage the top end of Renown.  As of right now, it's treating it as if you aren't going to gain anymore with Renown once it gets to the top end.

I'll work on fixes, but it may take a while to get updated for that because I'll need to test some changes to the code.  I'm almost there with Tuskarr, but I don't want to make further changes I can't test right away.

**Comment by Epidemedabear** [comment]
Thats cool, it works well enough for now :) If you want anything tested again like this, at least for Tuskarr Im miles away from hitting cap with the others, msg me or something here.

**Comment by mightykong** [comment]
Will do, I'm going to push this change as r63, and going to close this, but I'll open another issue around fixing the Renown at cap concerns
